name: Push to feature branch

on:
  push:
    branches:
      - 'feature/**'

jobs:
  push-to-org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install SFDX CLI'
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    - name: 'Get authentication url'
      shell: bash
      run: |
        echo ${{ secrets.AUTHORIZED_URL}} > ./AUTHORIZED_URL.txt
    - name: 'Authenticate to development org'
      run: sfdx auth:sfdxurl:store -f ./AUTHORIZED_URL.txt -s -a development
    - name: 'Deploy source to org'
      run: |
        sfdx force:source:deploy -p
          